apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flagger
  namespace: istio-system
spec:
  releaseName: flagger
  chart:
    repository: https://flagger.app
    name: flagger
    version: 1.1.0
  values:
    meshProvider: istio
    metricsServer: http://prometheus.istio-system:9090
    slack:
      user: flagger
      channel: general
      url: https://hooks.slack.com/services/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